### ISSUE TITLE
Can't upload to a specific server.

### ISSUE THREAD

**Issue by jfillon** [la-haute-societe/ssh-deploy-release#1]
Connect to <server>.com
Connected

Compress release
Archive created : 5.23 MB

Create release folder on remote
 - /var/www/releases/<my-path>/2017-06-13-00-50-43-443-UTC

Remote command : mkdir -p /var/www/releases/<my-path>/2017-06-13-00-50-43-443-UTC
chmod ugo+w /var/www/releases/<my-path>/2017-06-13-00-50-43-443-UTC
Done

Upload archive to remote
⠸ Uploadingbuffer.js:262
  throw new TypeError(kFromErrorMsg);
  ^

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:262:9)
    at Function.Buffer.from (buffer.js:101:10)
    at new Buffer (buffer.js:80:17)
    at onNEWKEYS (/Users/.../.../node_modules/scp2/node_modules/ssh2/lib/Connection.js:2282:29)
    at Parser.<anonymous> (/Users/.../.../node_modules/scp2/node_modules/ssh2/lib/Connection.js:123:5)
    at emitNone (events.js:86:13)
    at Parser.emit (events.js:185:7)
    at Parser.parsePacket (/Users/.../.../node_modules/scp2/node_modules/ssh2/lib/Parser.js:468:12)
    at Parser.execute (/Users/.../.../node_modules/scp2/node_modules/ssh2/lib/Parser.js:249:14)
    at Socket.<anonymous> (/Users/.../.../node_modules/scp2/node_modules/ssh2/lib/Connection.js:523:18)

**Comment by maxime-colin** [comment]
I can't reproduce this problem. It seems that the issue comes from this package : https://github.com/mscdex/ssh2
