### ISSUE TITLE
Error while compressing in archive mode

### ISSUE THREAD

**Issue by GuiguiCucu** [la-haute-societe/ssh-deploy-release#19]
When I execute `yarn deployator deploy --environment=review --branch="master" --debug` I get this error :

```
Compress release
Error while compressing
/Users/guillaume.c/Documents/projets/zicplace/marketplace/workspace/node_modules/ssh-deploy-release/dist/ssh-deploy-release.js:147
      throw err;
      ^

Error: size mismatch
    at Sink.<anonymous> (/Users/guillaume.c/Documents/projets/zicplace/marketplace/workspace/node_modules/tar-stream/pack.js:174:23)
    at Sink.f (/Users/guillaume.c/Documents/projets/zicplace/marketplace/workspace/node_modules/once/once.js:25:25)
    at Sink.onfinish (/Users/guillaume.c/Documents/projets/zicplace/marketplace/workspace/node_modules/end-of-stream/index.js:31:27)
    at Sink.emit (events.js:215:7)
    at finishMaybe (/Users/guillaume.c/Documents/projets/zicplace/marketplace/workspace/node_modules/tar-stream/node_modules/readable-stream/lib/_stream_writable.js:620:14)
    at endWritable (/Users/guillaume.c/Documents/projets/zicplace/marketplace/workspace/node_modules/tar-stream/node_modules/readable-stream/lib/_stream_writable.js:629:3)
    at Sink.Writable.end (/Users/guillaume.c/Documents/projets/zicplace/marketplace/workspace/node_modules/tar-stream/node_modules/readable-stream/lib/_stream_writable.js:567:22)
    at Readable.onend (/Users/guillaume.c/Documents/projets/zicplace/marketplace/workspace/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:299:28)
    at Readable.emit (events.js:215:7)
error Command failed with exit code 1.
```

Here is my config file :

```
"use strict";

module.exports = function (options) {
    return {
        common: {
            localPath: process.cwd(),
            share: {},
            exclude: [
                '.git'
            ],
            create: [],
            makeWritable: [
                'composer.json',
                'composer.lock',
                'vendor',
                'web',
            ],
            debug: true,
        },
        environments: {
            review: {
                host: 'myhost.com',
                username: 'username',
                password: 'pwd',
                deployPath: '/my/path/' + options.get('branch'),
                allowRemove: true
            },
        }
    };
};
```

Thanks

**Comment by nstCactus** [comment]
We'll fix this as soon as possible. In the mean time, we documented how to work around this. See the [README.md](https://github.com/la-haute-societe/ssh-deploy-release/#optionslocalpath) for more details.
